"""initial integrated schema and observed fares

Revision ID: 7a6e54d68711
Revises:
Create Date: 2026-09-28 13:43:07.571312

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a6e54d68711"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flights",
        sa.Column("amadeus_id", sa.String(length=255), nullable=True),
        sa.Column("airline_code", sa.String(length=10), nullable=False),
        sa.Column("airline_name", sa.String(length=100), nullable=False),
        sa.Column("flight_number", sa.String(length=20), nullable=False),
        sa.Column("departure_airport", sa.String(length=10), nullable=False),
        sa.Column("arrival_airport", sa.String(length=10), nullable=False),
        sa.Column("departure_time", sa.DateTime(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False, comment="비행 시간 (분)"),
        sa.Column("stops", sa.Integer(), nullable=False, comment="경유 횟수"),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column("price_krw", sa.Float(), nullable=False, comment="가격 (원화)"),
        sa.Column("price_jpy", sa.Float(), nullable=True, comment="가격 (엔화)"),
        sa.Column(
            "cabin_class",
            sa.String(length=20),
            nullable=False,
            comment="economy, premium_economy, business, first",
        ),
        sa.Column("available_seats", sa.Integer(), nullable=True),
        sa.Column(
            "baggage_allowance",
            sa.String(length=100),
            nullable=True,
            comment="20kg, 2PC 등",
        ),
        sa.Column(
            "raw_data", sa.JSON(), nullable=True, comment="Amadeus API 원본 데이터"
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flights_airline_code"), "flights", ["airline_code"], unique=False
    )
    op.create_index(
        op.f("ix_flights_amadeus_id"), "flights", ["amadeus_id"], unique=True
    )
    op.create_index(
        op.f("ix_flights_arrival_airport"), "flights", ["arrival_airport"], unique=False
    )
    op.create_index(
        op.f("ix_flights_departure_airport"),
        "flights",
        ["departure_airport"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flights_departure_time"), "flights", ["departure_time"], unique=False
    )
    op.create_index(op.f("ix_flights_id"), "flights", ["id"], unique=False)
    op.create_index(
        op.f("ix_flights_price_krw"), "flights", ["price_krw"], unique=False
    )
    op.create_table(
        "price_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("offer_id", sa.String(length=200), nullable=True),
        sa.Column("search_conditions", sa.JSON(), nullable=False),
        sa.Column("fare_conditions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_observation_observed_at",
        "price_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_observation_route_departure",
        "price_observations",
        ["origin", "destination", "departure_date"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "flight_searches",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("departure_airport", sa.String(length=10), nullable=False),
        sa.Column("arrival_airport", sa.String(length=10), nullable=False),
        sa.Column("departure_date", sa.DateTime(), nullable=False),
        sa.Column(
            "return_date", sa.DateTime(), nullable=True, comment="편도인 경우 null"
        ),
        sa.Column("passengers", sa.Integer(), nullable=False),
        sa.Column("cabin_class", sa.String(length=20), nullable=False),
        sa.Column(
            "max_price", sa.Integer(), nullable=True, comment="최대 가격 필터 (원화)"
        ),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column(
            "search_params", sa.JSON(), nullable=True, comment="전체 검색 파라미터"
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_searches_id"), "flight_searches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_flight_searches_user_id"), "flight_searches", ["user_id"], unique=False
    )
    op.create_table(
        "price_histories",
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("price_krw", sa.Float(), nullable=False, comment="가격 (원화)"),
        sa.Column("price_jpy", sa.Float(), nullable=True, comment="가격 (엔화)"),
        sa.Column(
            "available_seats", sa.Integer(), nullable=True, comment="남은 좌석 수"
        ),
        sa.Column("source", sa.String(length=50), nullable=False, comment="가격 출처"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_histories_flight_id"),
        "price_histories",
        ["flight_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_histories_id"), "price_histories", ["id"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column(
            "score", sa.Float(), nullable=False, comment="전체 추천 점수 (0-100)"
        ),
        sa.Column("rank", sa.Integer(), nullable=False, comment="추천 순위"),
        sa.Column("reason", sa.Text(), nullable=False, comment="추천 이유 (AI 생성)"),
        sa.Column(
            "price_analysis", sa.Text(), nullable=True, comment="가격 분석 (AI 생성)"
        ),
        sa.Column(
            "value_score", sa.Float(), nullable=True, comment="가성비 점수 (0-100)"
        ),
        sa.Column(
            "time_score", sa.Float(), nullable=True, comment="시간 효율성 점수 (0-100)"
        ),
        sa.Column(
            "comfort_score", sa.Float(), nullable=True, comment="편의성 점수 (0-100)"
        ),
        sa.Column(
            "ai_model",
            sa.String(length=50),
            nullable=False,
            comment="사용된 AI 모델 (gpt-4.1, claude-3 등)",
        ),
        sa.Column("ai_response", sa.JSON(), nullable=True, comment="AI 원본 응답"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_flight_id"),
        "recommendations",
        ["flight_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_id"), "recommendations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_rank"), "recommendations", ["rank"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "preferred_airlines",
            sa.JSON(),
            nullable=True,
            comment="선호 항공사 코드 리스트 ['NH', 'JL']",
        ),
        sa.Column(
            "avoided_airlines",
            sa.JSON(),
            nullable=True,
            comment="기피 항공사 코드 리스트",
        ),
        sa.Column("preferred_cabin_class", sa.String(length=20), nullable=False),
        sa.Column(
            "max_stops", sa.Integer(), nullable=False, comment="최대 허용 경유 횟수"
        ),
        sa.Column(
            "preferred_departure_time",
            sa.String(length=20),
            nullable=True,
            comment="morning, afternoon, evening, night",
        ),
        sa.Column(
            "price_priority",
            sa.Integer(),
            nullable=False,
            comment="가격 우선순위 (0-10)",
        ),
        sa.Column(
            "time_priority",
            sa.Integer(),
            nullable=False,
            comment="시간 우선순위 (0-10)",
        ),
        sa.Column(
            "comfort_priority",
            sa.Integer(),
            nullable=False,
            comment="편의성 우선순위 (0-10)",
        ),
        sa.Column("notification_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "price_alert_threshold",
            sa.Float(),
            nullable=False,
            comment="가격 하락 알림 임계값 (%)",
        ),
        sa.Column("settings", sa.JSON(), nullable=True, comment="추가 사용자 설정"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_preferences_id"), "user_preferences", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_rank"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_flight_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_price_histories_id"), table_name="price_histories")
    op.drop_index(op.f("ix_price_histories_flight_id"), table_name="price_histories")
    op.drop_table("price_histories")
    op.drop_index(op.f("ix_flight_searches_user_id"), table_name="flight_searches")
    op.drop_index(op.f("ix_flight_searches_id"), table_name="flight_searches")
    op.drop_table("flight_searches")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_observation_route_departure", table_name="price_observations")
    op.drop_index("ix_observation_observed_at", table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index(op.f("ix_flights_price_krw"), table_name="flights")
    op.drop_index(op.f("ix_flights_id"), table_name="flights")
    op.drop_index(op.f("ix_flights_departure_time"), table_name="flights")
    op.drop_index(op.f("ix_flights_departure_airport"), table_name="flights")
    op.drop_index(op.f("ix_flights_arrival_airport"), table_name="flights")
    op.drop_index(op.f("ix_flights_amadeus_id"), table_name="flights")
    op.drop_index(op.f("ix_flights_airline_code"), table_name="flights")
    op.drop_table("flights")
    # ### end Alembic commands ###
